### PR TITLE
Change to app stat to grid instead of flex

### PR DESCRIPTION
**Pull request by TalOrlanczyk**
what I did:
1. I change the flex to grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); so as the screen shrink so be able to see better the cards.
2. add some constant 
3.loading screen

why I did it?
1. personal preference.
I prefer that stuff to use a grid instead of flex because a grid gives you two-dimension instead of one and this can help you place an item on the screen much easier.
2.I add some constant in the API file to make the code more maintainable.
3. I add a loading screen so until the data finish fetch you don't print all the page (it's not necessary to print all the page if you don't have data ).

P.S
your code looks really good and enjoy to see it.
and if you approve push it to the github pages

### CODE REVIEW

**Comment by abhilash-ss** [comment]
@TalOrlanczyk 
Please follow the BEM method of writing styles.
And also you can write nested classes in the SCSS style sheet

**Comment by TalOrlanczyk** [comment]
@itsmeAB do you mean the loader?

**Comment by TalOrlanczyk** [comment]
well now I use the nested className as I think I use the BEM method if not I want to understand what you mean

**Comment by abhilash-ss** [comment]
@TalOrlanczyk 
please take a look on this http://getbem.com/naming/
and also you can check on the MapCircle component: https://github.com/itsmeAB/covid-19-tracker/tree/master/src/components/MapCircle
please feel free to add your suggestions and comments on this.

**Comment by TalOrlanczyk** [comment]
As I see i pretty much done the same in the loader as its the only thing I create from scratch

**Pull request merged**
